sonar.projectKey=tu-proyecto
sonar.projectName=Mi App Vulnerable
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.venv/**,**/migrations/**
sonar.python.version=3
sonar.sourceEncoding=UTF-8